name: macOS

on: [push, pull_request]

jobs:
  xcode:
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Cache vcpkg
      uses: actions/cache@v2
      id: cache-vcpkg
      with:
        path: build/vcpkg_installed/
        key: vcpkg-x64-osx

    - name: Create Build Environment
      if: ${{ !steps.cache-vcpkg.outputs.cache-hit }}
      run: cmake -E make_directory build

    - name: Configure
      shell: pwsh
      working-directory: build/
      run: |
        $vcpkgToolchain = Join-Path $env:VCPKG_ROOT './scripts/buildsystems/vcpkg.cmake' -Resolve
        $cmakeBuildType = '${{ matrix.config }}'

        cmake "-DCMAKE_TOOLCHAIN_FILE=$vcpkgToolchain" "-DCMAKE_BUILD_TYPE=$cmakeBuildType" ${{ github.workspace }}

    - name: Build
      working-directory: build/
      run: cmake --build . -j -v

    - name: Test
      working-directory: build/
      run: ctest --output-on-failure
